---
- name: Install Go packages for the current user
  become: false
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ golang_home }}/{{ golang_path }}/bin"
    GOPATH: "{{ golang_home }}/{{ golang_path }}"
    GO111MODULE: "on"
  block:
    - name: Install packages with major version tag
      command: "go install {{ item.name }}"
      with_items: "{{ golang_packages }}"
      register: go_get_result
      changed_when:
        - '"downloading" in go_get_result.stderr'
        - go_get_result.rc != 2
      when:
        - '"@" in item.name'
