#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT=$(dirname "$DIR")

ROLE_NAME="$(basename "$PROJECT_ROOT")"

set -euo pipefail

cd "$DIR"

user="test"
repository="${ROLE_NAME}"
ansible_version="<2.9.0"

# Generate Dockerfile from Dockerfile.template
update_docker_image() {
    local docker_image=$1
    local docker_tag=$2
    local target_dir
    local target_file
    target_dir="images/${docker_tag}"
    target_file="${target_dir}/Dockerfile"
    echo "*** Updating ${target_dir}/Dockerfile"
    mkdir -p "${target_dir}"
    if test "$(uname)" = "Darwin"; then
        sed -E \
            -e 's!%%FROM%%!'"$docker_image:$docker_tag"'!g' \
            -e 's!%%USER%%!'"$user"'!g' \
            -e 's!%%REPOSITORY%%!'"$repository"'!g' \
            -e 's!%%ANSIBLE_VERSION%%!'"$ansible_version"'!g' \
            "Dockerfile.template" >"${target_file}"
    else
        sed -r \
            -e 's!%%FROM%%!'"$docker_image:$docker_tag"'!g' \
            -e 's!%%USER%%!'"$user"'!g' \
            -e 's!%%REPOSITORY%%!'"$repository"'!g' \
            -e 's!%%ANSIBLE_VERSION%%!'"$ansible_version"'!g' \
            "Dockerfile.template" >"${target_file}"
    fi
}

ubuntu_releases=(xenial bionic eoan)
for tag in "${ubuntu_releases[@]}"; do
    update_docker_image "ubuntu" "${tag}"
done

debian_releases=(buster)
for tag in "${debian_releases[@]}"; do
    update_docker_image "debian" "${tag}"
done
